package org.example.publickeyinfrastructure.Services.Infrastucture;

import org.example.publickeyinfrastructure.DTOs.Infrastructure.OrganisationDTO;
import org.example.publickeyinfrastructure.Entities.Infrastructure.Organisation;
import org.example.publickeyinfrastructure.Repositories.OrganisationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

@Service
@Transactional
public class OrganisationService {

    @Autowired
    private OrganisationRepository organisationRepository;

    public List<Organisation> getAllOrganisations() {
        return organisationRepository.findAll();
    }

    public OrganisationDTO convertToDTO(Organisation organisation) {
        return new OrganisationDTO(organisation);
    }

    public List<OrganisationDTO> convertToDTOList(List<Organisation> organisations) {
        return organisations.stream()
            .map(this::convertToDTO)
            .collect(Collectors.toList());
    }

    public Organisation createOrganisation(OrganisationDTO organisationDTO) {
        Organisation organisation = new Organisation(
            null, // ID will be generated by the database
            organisationDTO.getName(),
            organisationDTO.getUnit(),
            organisationDTO.getCountry()
        );
        return organisationRepository.save(organisation);
    }
}


